---
title: "Class Code for 0316"
author: "Sanjeev Kumar"
date: "March 16, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Linear Regression

## Import and Clean Data

```{r}
#Code for importing and cleaning data

project_list <- read.csv("ProjectA_Listings2013.csv")



```



```{r}
#Convert columns to factors
project_list$is_homeowner <- as.factor(project_list$is_homeowner)
project_list$prosper_rating <- as.factor(project_list$prosper_rating)
project_list$scorex <- as.factor(project_list$scorex)
project_list$income_verifiable <- as.factor(project_list$income_verifiable)
project_list$employment_status_description <- as.factor(project_list$employment_status_description)
project_list$occupation <- as.factor(project_list$occupation)
project_list$loan_status <- as.factor(project_list$loan_status)
project_list$listing_term <- as.factor(project_list$listing_term)
project_list$prosper_score <- as.factor(project_list$prosper_score)
project_list$listing_category_id <- as.factor(project_list$listing_category_id)
project_list$income_range <- as.factor(project_list$income_range)
project_list$lender_indicator <- as.factor(project_list$lender_indicator)

#lets change the labels for the factors
project_list$is_homeowner <- factor(project_list$is_homeowner, labels = c("TRUE", "FALSE"))
project_list$prosper_rating <- factor(project_list$prosper_rating, labels = c("B", "D", "E", "HR", "A", "AA", "C"))
project_list$scorex <- factor(project_list$scorex, labels = c("702-723", "650-664", "620-639", "640-649", "748-777", "665-689", "778+", "600-619", "690-701", "724-747", "< 600"))
project_list$income_verifiable <- factor(project_list$income_verifiable, labels = c("TRUE", "FALSE"))
project_list$employment_status_description <- factor(project_list$employment_status_description, labels = c("Employed", "Other", "Full-time", "Self-employed", "Not employed", "Part-time", "Retired"))
project_list$occupation <- factor(project_list$occupation, labels = c("Other", "Sales - Retail", "Computer Programmer", "Teacher", "Executive", "Realtor", "Tradesman - Mechanic", "Medical Technician", "Administrative Assistant", "Pharmacist", "Accountant/CPA", "Professional", "Attorney", "Nurse (RN)", "Police Officer/Correction Officer", "Retail Management", "Analyst", "Construction", "Sales - Commission", "Skilled Labor", "Clerical", "Civil Service", "Engineer - Electrical", "Truck Driver", "Military Enlisted", "Waiter/Waitress", "Engineer - Mechanical", "Food Service Management", "Laborer", "Social Worker", "Architect", "Fireman", "Tradesman - Electrician", "Doctor", "Investor", "Bus Driver", "Chemist", "Food Service", "Biologist", "Military Officer", "Tradesman - Plumber",
"Principal", "Nurse (LPN)", "Postal Service", "Teacher's Aide", "Professor", "Dentist", "Pilot - Private/Commercial", "Engineer - Chemical", "Landscaping", "Religious", "Student - College Graduate Student", "Homemaker", "Scientist", "Clergy", "Judge", "Nurse's Aide", "Tradesman - Carpenter", "Car Dealer", "Flight Attendant", "Student - Community College", "Psychologist", "Student - College Senior", "Student - College Junior", "Student - College Freshman", "Student - College Sophomore", "Student - Technical School", ""
))

#Remove NAs
project_list$months_employed <- ifelse(is.na(project_list$months_employed),mean(project_list$months_employed,na.rm = TRUE),project_list$months_employed)
project_list$installment_balance <- ifelse(is.na(project_list$installment_balance),mean(project_list$installment_balance,na.rm = TRUE),project_list$installment_balance)

#lets take a look at structure and summary
str(project_list)
summary(project_list)

```

```{r}
unique(project_list$occupation, incomparables = FALSE)
```


## Regression Models

### Main Effects Model

```{r}

#All relevant variables to predict borrower rate
model1 <- lm(borrower_rate ~ number_of_days	+ principal_balance	+ loan_status	+ amount_funded	+ prosper_rating	+ listing_term	+ listing_monthly_payment	+ scorex	+ prosper_score	+ listing_category_id	+income_range	+ stated_monthly_income	+ income_verifiable	+ dti_wprosper_loan	+ months_employed	+ lender_indicator	+ monthly_debt	+ current_delinquencies	+ delinquencies_last7_years	+ public_records_last10_years	+ public_records_last12_months	+ credit_lines_last7_years	+ inquiries_last6_months	+ amount_delinquent	+ current_credit_lines	+ open_credit_lines	+  bankcard_utilization	+ total_open_revolving_accounts	+ installment_balance	+ real_estate_balance	+ revolving_balance	+ real_estate_payment	+ revolving_available_percent	+ total_inquiries	+  total_trade_items	+ satisfactory_accounts	+  now_delinquent_derog	+ was_delinquent_derog	+ delinquencies_over30_days	+ delinquencies_over60_days	+ delinquencies_over90_days	+ is_homeowner + employment_status_description + occupation	, data = project_list)
summary(model1)

#Only significant variables to predict borrower rate
model2 <- lm(borrower_rate ~ number_of_days	+ principal_balance	+ loan_status	+ amount_funded	+ prosper_rating	+ listing_term	+ listing_monthly_payment	+ dti_wprosper_loan + lender_indicator	+ inquiries_last6_months	+ open_credit_lines	+  bankcard_utilization	+ revolving_balance	+ revolving_available_percent	+ total_inquiries	+ delinquencies_over30_days	+ is_homeowner, data = project_list)
summary(model2)
```
# Logistic Regression

## Import and Clean Data

```{r}
#Create new column for default or not
project_list$default_status <- 0
project_list$default_status <- ifelse((project_list$loan_status == 2 | project_list$loan_status == 3), 1, project_list$default_status)
project_list$default_status <- as.integer(project_list$default_status)

str(project_list)
summary(project_list)


#logistic regression with significant variables
logit.model <- glm(default_status ~ number_of_days + principal_balance + amount_funded + prosper_rating + borrower_rate + listing_term + listing_monthly_payment + lender_indicator + delinquencies_last7_years + inquiries_last6_months + bankcard_utilization + revolving_balance + satisfactory_accounts,data = project_list, family = "binomial")

summary(logit.model)

```




